ansible_become_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38323663646134363365656461323037356639663533646333636237646439376664373433373434
          6565376339333762316330653730316537343239656433360a383033666164363165316332396132
          36616266656330343037373134663337336232393732616663303439343563636630643137653536
          6133343832653462340a626639353530316538653164356363376234626165346137653530393361
          6230
